version: 2.1
workflows:
  marc2bibframe2-xspec-tests:
    jobs:
      - build:
          context:
            - xspec-env-vars
            - docker-hub-creds
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
        auth:
          username: $DH_USERNAME
          password: $DH_PASSWORD
    steps:
      - checkout
      - run:
          name: Install testing prerequisites
          command: |
            # sudo apt-get update
            mkdir /tmp/saxon/
            mkdir /tmp/saxon/lib/
            
            #cd /tmp/saxon/
            #curl -o Saxon-HE.zip -L https://github.com/Saxonica/Saxon-HE/releases/download/SaxonHE12-4/SaxonHE12-4J.zip
            #unzip Saxon-HE.zip

            curl -o /tmp/saxon/lib/xmlresolver-5.2.2.jar https://repo1.maven.org/maven2/org/xmlresolver/xmlresolver/5.2.2/xmlresolver-5.2.2.jar
            curl -o /tmp/saxon/lib/xmlresolver-5.2.2-data.jar https://repo1.maven.org/maven2/org/xmlresolver/xmlresolver/5.2.2/xmlresolver-5.2.2-data.jar  
            curl -o /tmp/saxon/lib/jline-2.14.6.jar https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6.jar
            curl -o /tmp/saxon/saxon-He-${SAXON_VERSION}.jar https://repo1.maven.org/maven2/net/sf/saxon/Saxon-HE/${SAXON_VERSION}/Saxon-HE-${SAXON_VERSION}.jar 
            curl -o /tmp/saxon/saxon-He-${SAXON_VERSION}-xqj.jar https://repo1.maven.org/maven2/net/sf/saxon/Saxon-HE/${SAXON_VERSION}/Saxon-HE-${SAXON_VERSION}-xqj.jar 
            curl -o /tmp/saxon/saxon-He-${SAXON_VERSION}-test.jar https://repo1.maven.org/maven2/net/sf/saxon/Saxon-HE/${SAXON_VERSION}/Saxon-HE-${SAXON_VERSION}-test.jar 
            
            cd /tmp/saxon/
            ls -l
            ls -l lib/*
            
            git clone https://github.com/xspec/xspec.git /tmp/xspec
      - run:
          name: Run standard XSpec test suite
          command: "$XSPEC test/marc2bibframe2.xspec"
      - run:
          name: Run LoC-specific test suite
          command: "$XSPEC test/ConvSpec-DLC.xspec"
      - store_artifacts:
          path: test/xspec/marc2bibframe2-result.html
          destination: xspec-tests/marc2bibframe2-result.html
      - store_artifacts:
          path: test/xspec/ConvSpec-DLC-result.html
          destination: xspec-tests/ConvSpec-DLC-result.html
